### PR TITLE
Create custom vision deployment template

### PR DESCRIPTION
**Pull request by avkewalr-msft**
@naiteeks, @anilmur  - review and sign off next week when possible

### CODE REVIEW

**Review by johndeu — APPROVED** [review]

**Comment by johndeu** [comment]
@avkewalr-msft  - I'm not the merger on this repo. 
I'm not sure who setup this repo, as it should be set to the correct team for Media Services Write sample access so we can review and merge changes.

**Comment by avkewalr-msft** [comment]
@gadamilan - @johndeu  has approved. This should be good to merge

**Comment by johndeu** [comment]
#sign-off  @gadamilan

**Comment by naiteeks** [comment]
can we add an entry in the [readme ](https://github.com/Azure-Samples/live-video-analytics-iot-edge-csharp/blob/master/src/edge/readme.md) file as well for this file?

**Comment by avkewalr-msft** [comment]
https://github.com/Azure-Samples/live-video-analytics-iot-edge-csharp/pull/22

@naiteeks - done

**Comment by naiteeks** [comment]
#sign-off

**Pull request merged**
